### ISSUE TITLE
关于rect标注中score的疑问

### ISSUE THREAD

**Issue by Puppet097** [graspnet/rectangle-graspnet-multiObject-multiGrasp#10]
请问为什么此处data_preprocessing中筛选score<0.2的数据，而graspnetAPI中loadgrasp中读取rect数据筛选方式为score>=1.1 - fric_coef_thresh，比较疑惑datasets中给的rect标注里可行抓取的score应该越高还是越低？

**Comment by Fang-Haoshu** [comment]
你好，这是历史遗留的bug，应该是大于0.8，目前所有graspnetAPI读取得到的score都是分数越高越好
