### ISSUE TITLE
graspnetAPI中的copy rect label创建的folder名字是rect，这里里用的名字是rectangle_grasp

### ISSUE THREAD

**Issue by cww97** [graspnet/rectangle-graspnet-multiObject-multiGrasp#2]
https://github.com/graspnet/rectangle-graspnet-multiObject-multiGrasp/blob/master/data_process/script/data_preprocessing.py#L64

64,66,69 三行
我改了这三行能正确运行data_preprocessing了，

**Comment by shengxucs** [comment]
已修改，谢谢~
